# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Command": "00_core.ipynb",
         "Shell": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{user}.github.io/pyshell/"

git_url = "https://github.com/{user}/pyshell/tree/{branch}/"

def custom_doc_links(name): return None
