# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Command": "00_core.ipynb",
         "Shell": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ababino.github.io/pyshell/"

git_url = "https://github.com/ababino/pyshell/tree/master/"

def custom_doc_links(name): return None
